# Generated by Django 3.2.6 on 2021-08-21 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.FileField(null=True, upload_to='postimages'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
